CREATE TABLE rsvp (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '',
  phone TEXT NOT NULL DEFAULT '',
  attending TEXT NOT NULL DEFAULT 'yes',
  guests INTEGER NOT NULL DEFAULT 1,
  menu TEXT NOT NULL DEFAULT 'meat',
  diet_note TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);